applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),
    path(
        'listar-todo/',
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path(
        'listar-by-area/<shorname>/',
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),
    path(
        'listar-empleados-admin/',
        views.ListAllEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/',
        views.SuccessView.as_view(),
        name='correcto'
    ),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings  # para multimedia subir imagenes
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos laas urls de la app depa
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.persona.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento

# Create your models here.
from ckeditor.fields import RichTextField


class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades Empleados'

    def __str__(self):
        return str(self.id) + '-' + self.habilidad


class Empleado(models.Model):
    """ modelo para tabla empleados """

    JOB_CHOICES = (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRAOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'OTRO'),
    )

    first_name = models.CharField('Nombres', max_length=50)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField(
        'Nombres completos',
        max_length=120,
        blank=True)
    job = models.CharField('Trabajo', max_length=50, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    #hoja_vida = RichTextField()

    class Meta:
        verbose_name = 'Mi Empleado'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['-first_name', 'last_name']
        unique_together = ('first_name', 'departamento')

    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name

applications/persona/forms.py
from django import forms
from .models import Empleado


class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/persona/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DeleteView,
    CreateView,
    TemplateView,
    UpdateView,
    DetailView
)
# models
from .models import Empleado
# forms
from .forms import EmpleadoForm


class InicioView(TemplateView):
    """ vista que carga la pagina de inicio """
    template_name = 'inicio.html'


class ListAllEmpleados(ListView):
    template_name = 'persona/list_all.html'
    paginate_by = 4
    ordering = 'first_name'
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            first_name__icontains=palabra_clave,

        )
        return lista


class ListAllEmpleadosAdmin(ListView):
    template_name = 'persona/lista_empleados.html'
    paginate_by = 5
    ordering = 'first_name'
    context_object_name = 'empleados'

    model = Empleado


# mostar empleados y sus ddepartamentos a los que pertenece


class ListByAreaEmpleado(ListView):
    template_name = 'persona/list_by_area.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        area = self.kwargs['shorname']
        lista = Empleado.objects.filter(
            departamento__shor_name=area
        )
        return lista


class ListEmpleadosByKword(ListView):
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        print('**********************')
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            first_name=palabra_clave
        )
        return lista

# Listar habilidades de un empleado


class ListHabilidadesEmpleado(ListView):
    template_name = 'persona/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(id=3)

        return empleado.habilidades.all()


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        return context


class SuccessView(TemplateView):
    template_name = "persona/success.html"


class EmpleadoCreateView(CreateView):
    template_name = "persona/add.html"
    model = Empleado
    form_class = EmpleadoForm

    success_url = reverse_lazy('persona_app:empleados_admin')

    def form_valid(self, form):
        # logica del prceso para validar
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    template_name = "persona/update.html"
    model = Empleado
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',

    ]

    success_url = reverse_lazy('persona_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('******** METODO POST **********')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        # logica del prceso para validar
        print('********** METODO FORM VALID************')

        return super(EmpleadoUpdateView, self).form_valid(form)


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"
    success_url = reverse_lazy('persona_app:empleados_admin')

templates/persona/add.html
{% extends 'base.html' %}


{% block title %}
Registrar empleado
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Empleado</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data"> {% csrf_token %}

            <div class="medium-6 cell">
                <label>Nombres:
                    {{form.first_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                    {{form.last_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Trabajo:
                    {{form.job}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                    {{form.departamento}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Habilidades:
                    {{form.habilidades}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Foto:
                    {{form.avatar}}
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button success">Guardar</button>
            </div>



        </form>
    </div>
</div>

{% endblock content %}

templates/persona/by_kword.html
<h1>Buscar empleados por palabra</h1>

<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="ingrese palabra">
    <button type="submit">Buscar</button>
</form>

<h3>Lista resultados</h3>
<ul>
    {% for e in empleados %}
    <li>
        {{e}}
    </li>

    {% endfor %}
</ul>

templates/persona/delete.html
{% extends 'base.html' %}

{% block title %}
Eliminar empleado
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar empleado: {{object.first_name}}</h1>

        <form class="cell" method="POST">{% csrf_token %}
            <div class="callout secondary">
                <h5>¿Desea eliminar este empleado?</h5>
                <p>Si emlimina se borrara de la base de datos</p>
                <button type="submit" class="alert button">Confirmar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
{{ object.full_name }}

{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-4 card" style="width: 300px; margin-top:1rem;">
            <div class="card-divider">
                {{ empleado.get_job_display }}
                <!--nombre empleado modelen misnuscula-->
            </div>

            {% if empleado.avatar %}
            <img src="{{ empleado.avatar.url }}">
            {% else %}
            <img src=" {% static 'img/1.jpg' %}">
            {% endif %}


            <div class="card-section">
                <h4>{{ empleado.full_name}}</h4>

                <p>{{ empleado.last_name }}</p>
                <p>{{ empleado.departamento.shorname }}</p>
                <p><span class="label">Habilidades</span></p>
                <ul class="vertical menu">

                    {% for h in empleado.habilidades.all %}
                    <li>{{ h.habilidad }}</li>
                    <!--models habilidadllamas-->
                    {% endfor %}

                </ul>

            </div>
        </div>
    </div>
</div>


{% endblock content %}



<h1>Detalles de un empleado {{titulo}}</h1>

<h3>Todods los datos</h3>
<p>{{empleado.first_name}}</p>
<p>{{empleado.last_name}}</p>
<p>{{empleado.departamento}}</p>
<p>{{empleado.habilidades}}</p>

templates/persona/habilidades.html
<h1>Habilidades de empleado</h1>
<ul>
    {% for h in habilidades %}
    <li>{{h}}</li>
    {% endfor %}
</ul>

templates/persona/list_all.html
{% extends 'base.html' %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="Buscar Empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDO</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>

        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                    {% endif %}


                    {% for pagina in paginator.page_range %}
                    {% ifequal pagina page_obj.number  %}
                    <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                    {% else %}
                    <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                    {% endifequal %}
                    {% endfor%}


                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>

    </div>

</div>

{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block title %}
Lista de empleados por departamento
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <div class="cell">Empleados por Area:</div>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDO</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}

<h1>Lista Empleados por Departamento</h1>

<ul>
    {% for e in object_list %}
    <li>
        {{e}}
    </li>

    {% endfor %}
</ul>

templates/persona/lista_empleados.html
{% extends 'base.html' %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>

        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDO</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td>
                            <a class="button success" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a>
                        </td>
                        <td>
                            <a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>

        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                    {% endif %}


                    {% for pagina in paginator.page_range %}
                    {% ifequal pagina page_obj.number  %}
                    <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                    {% else %}
                    <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                    {% endifequal %}
                    {% endfor%}


                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>

    </div>

</div>

{% endblock content %}

templates/persona/success.html
<h1>Correcto, se guardaron correctamente</h1>

templates/persona/update.html
{% extends 'base.html' %}


{% block titulo %}
Editar empleado

{% endblock titulo %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar Empleado
        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres:
                        {{ form.first_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellidos:
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo:
                        {{ form.job}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Area:
                        {{ form.departamento }}
                    </label>
                </div>

                <label>Habilidades estra:
                    {{ form.habilidades }}
                </label>
        </div>
        <div class="cell">
            <button type="submit" class="success button">Guardar</button>
        </div>

        </form>
    </div>
</div>
</div>
{% endblock content %}